### ISSUE TITLE
Linux build failure in ADO pipeline

### ISSUE THREAD

**Issue by lorisercole** [microsoft/qdk-chemistry#661]
The latest run of the [python-wheels](https://github.com/microsoft/qdk-chemistry/blob/main/.pipelines/python-wheels.yaml) ADO pipeline produced build failures for all Linux jobs:
```
[136/136] : && /usr/bin/g++ -fPIC -march=x86-64-v3 -fPIC -Os -fvisibility=hidden -g -O3 -DNDEBUG  -flto=auto -shared  -o _core.cpython-312-x86_64-linux-gnu.so CMakeFiles/_core.dir/src/pybind11/data/data_class.cpp.o CMakeFiles/_core.dir/src/pybind11/data/symmetry/symmetry.cpp.o CMakeFiles/_core.dir/src/pybind11/data/symmetry/symmetry_blocked_scalar.cpp.o CMakeFiles/_core.dir/src/pybind11/data/symmetry/symmetry_blocked_tensor.cpp.o CMakeFiles/_core.dir/src/pybind11/data/symmetry/symmetry_blocked_index_set.cpp.o CMakeFiles/_core.dir/src/pybind11/data/symmetry/symmetry_blocked_sparse_map.cpp.o CMakeFiles/_core.dir/src/pybind11/data/element_data.cpp.o CMakeFiles/_core.dir/src/pybind11/data/orbitals.cpp.o CMakeFiles/_core.dir/src/pybind11/data/wavefunction.cpp.o CMakeFiles/_core.dir/src/pybind11/data/hamiltonian.cpp.o CMakeFiles/_core.dir/src/pybind11/data/settings.cpp.o CMakeFiles/_core.dir/src/pybind11/data/structure.cpp.o CMakeFiles/_core.dir/src/pybind11/data/basis_set.cpp.o CMakeFiles/_core.dir/src/pybind11/data/configuration.cpp.o CMakeFiles/_core.dir/src/pybind11/data/configuration_set.cpp.o CMakeFiles/_core.dir/src/pybind11/data/ansatz.cpp.o CMakeFiles/_core.dir/src/pybind11/data/stability_result.cpp.o CMakeFiles/_core.dir/src/pybind11/data/nuclear_gradients.cpp.o CMakeFiles/_core.dir/src/pybind11/data/nuclear_hessian.cpp.o CMakeFiles/_core.dir/src/pybind11/data/pauli_operator.cpp.o CMakeFiles/_core.dir/src/pybind11/data/majorana_mapping.cpp.o CMakeFiles/_core.dir/src/pybind11/data/serialization.cpp.o CMakeFiles/_core.dir/src/pybind11/data/lattice_graph.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/localizer.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/stability.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/mc.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/pmc.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/mcscf.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/hamiltonian.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/scf.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/nuclear_derivative.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/population_analysis.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/geometry_optimization.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/active_space.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/dynamical_correlation_calculator.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/effective_hamiltonian.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/davidson_solver.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/syev_solver.cpp.o CMakeFiles/_core.dir/src/pybind11/utils/logger.cpp.o CMakeFiles/_core.dir/src/pybind11/utils/valence_space.cpp.o CMakeFiles/_core.dir/src/pybind11/utils/orbital_rotation.cpp.o CMakeFiles/_core.dir/src/pybind11/utils/model_hamiltonians.cpp.o CMakeFiles/_core.dir/src/pybind11/utils/cube_generator.cpp.o CMakeFiles/_core.dir/src/pybind11/constants.cpp.o CMakeFiles/_core.dir/src/pybind11/qdk_scf_config.cpp.o CMakeFiles/_core.dir/src/pybind11/module.cpp.o  -Wl,-rpath,"\$ORIGIN:\$ORIGIN/..:"  qdk_build/libqdk_chemistry.a  _deps/libint2-build/libint2.a  _deps/ecpint-build/src/libecpint.a  _deps/ecpint-build/external/Faddeeva/libFaddeeva.a  _deps/gauxc-build/src/libgauxc.a  _deps/exchcxx-build/src/libexchcxx.a  _deps/integratorxx-build/src/libintegratorxx.a  /usr/local/lib/libhdf5_cpp.a  /usr/local/lib/libhdf5.a  /usr/lib/x86_64-linux-gnu/libz.so  /usr/lib/x86_64-linux-gnu/libdl.a  -lm  _deps/macis-build/src/macis/libmacis.a  _deps/lapackpp-build/liblapackpp.a  _deps/blaspp-build/libblaspp.a  /usr/local/lib/libflame.a  /usr/local/lib/libblis.a  -lm  _deps/macis-build/src/sparsexx/libsparsexx.a  _deps/spdlog-build/libspdlog.a && cd /workspace/qdk-chemistry/python/build/cp312-cp312-linux_x86_64 && /usr/bin/strip /workspace/qdk-chemistry/python/build/cp312-cp312-linux_x86_64/_core.cpython-312-x86_64-linux-gnu.so
FAILED: _core.cpython-312-x86_64-linux-gnu.so 
: && /usr/bin/g++ -fPIC -march=x86-64-v3 -fPIC -Os -fvisibility=hidden -g -O3 -DNDEBUG  -flto=auto -shared  -o _core.cpython-312-x86_64-linux-gnu.so CMakeFiles/_core.dir/src/pybind11/data/data_class.cpp.o CMakeFiles/_core.dir/src/pybind11/data/symmetry/symmetry.cpp.o CMakeFiles/_core.dir/src/pybind11/data/symmetry/symmetry_blocked_scalar.cpp.o CMakeFiles/_core.dir/src/pybind11/data/symmetry/symmetry_blocked_tensor.cpp.o CMakeFiles/_core.dir/src/pybind11/data/symmetry/symmetry_blocked_index_set.cpp.o CMakeFiles/_core.dir/src/pybind11/data/symmetry/symmetry_blocked_sparse_map.cpp.o CMakeFiles/_core.dir/src/pybind11/data/element_data.cpp.o CMakeFiles/_core.dir/src/pybind11/data/orbitals.cpp.o CMakeFiles/_core.dir/src/pybind11/data/wavefunction.cpp.o CMakeFiles/_core.dir/src/pybind11/data/hamiltonian.cpp.o CMakeFiles/_core.dir/src/pybind11/data/settings.cpp.o CMakeFiles/_core.dir/src/pybind11/data/structure.cpp.o CMakeFiles/_core.dir/src/pybind11/data/basis_set.cpp.o CMakeFiles/_core.dir/src/pybind11/data/configuration.cpp.o CMakeFiles/_core.dir/src/pybind11/data/configuration_set.cpp.o CMakeFiles/_core.dir/src/pybind11/data/ansatz.cpp.o CMakeFiles/_core.dir/src/pybind11/data/stability_result.cpp.o CMakeFiles/_core.dir/src/pybind11/data/nuclear_gradients.cpp.o CMakeFiles/_core.dir/src/pybind11/data/nuclear_hessian.cpp.o CMakeFiles/_core.dir/src/pybind11/data/pauli_operator.cpp.o CMakeFiles/_core.dir/src/pybind11/data/majorana_mapping.cpp.o CMakeFiles/_core.dir/src/pybind11/data/serialization.cpp.o CMakeFiles/_core.dir/src/pybind11/data/lattice_graph.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/localizer.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/stability.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/mc.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/pmc.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/mcscf.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/hamiltonian.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/scf.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/nuclear_derivative.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/population_analysis.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/geometry_optimization.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/active_space.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/dynamical_correlation_calculator.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/effective_hamiltonian.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/davidson_solver.cpp.o CMakeFiles/_core.dir/src/pybind11/algorithms/syev_solver.cpp.o CMakeFiles/_core.dir/src/pybind11/utils/logger.cpp.o CMakeFiles/_core.dir/src/pybind11/utils/valence_space.cpp.o CMakeFiles/_core.dir/src/pybind11/utils/orbital_rotation.cpp.o CMakeFiles/_core.dir/src/pybind11/utils/model_hamiltonians.cpp.o CMakeFiles/_core.dir/src/pybind11/utils/cube_generator.cpp.o CMakeFiles/_core.dir/src/pybind11/constants.cpp.o CMakeFiles/_core.dir/src/pybind11/qdk_scf_config.cpp.o CMakeFiles/_core.dir/src/pybind11/module.cpp.o  -Wl,-rpath,"\$ORIGIN:\$ORIGIN/..:"  qdk_build/libqdk_chemistry.a  _deps/libint2-build/libint2.a  _deps/ecpint-build/src/libecpint.a  _deps/ecpint-build/external/Faddeeva/libFaddeeva.a  _deps/gauxc-build/src/libgauxc.a  _deps/exchcxx-build/src/libexchcxx.a  _deps/integratorxx-build/src/libintegratorxx.a  /usr/local/lib/libhdf5_cpp.a  /usr/local/lib/libhdf5.a  /usr/lib/x86_64-linux-gnu/libz.so  /usr/lib/x86_64-linux-gnu/libdl.a  -lm  _deps/macis-build/src/macis/libmacis.a  _deps/lapackpp-build/liblapackpp.a  _deps/blaspp-build/libblaspp.a  /usr/local/lib/libflame.a  /usr/local/lib/libblis.a  -lm  _deps/macis-build/src/sparsexx/libsparsexx.a  _deps/spdlog-build/libspdlog.a && cd /workspace/qdk-chemistry/python/build/cp312-cp312-linux_x86_64 && /usr/bin/strip /workspace/qdk-chemistry/python/build/cp312-cp312-linux_x86_64/_core.cpython-312-x86_64-linux-gnu.so
/usr/bin/ld: /usr/local/lib/libblis.a(bla_rot.o): in function `crot_':
bla_rot.c:(.text+0x4d6): multiple definition of `crot_'; /usr/local/lib/libflame.a(crot.o):crot.c:(.text+0x0): first defined here
/usr/bin/ld: /usr/local/lib/libblis.a(bla_rot.o): in function `zrot_':
bla_rot.c:(.text+0x7f3): multiple definition of `zrot_'; /usr/local/lib/libflame.a(zrot.o):zrot.c:(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

*** CMake build failed
```
see: [Pipeline run](https://dev.azure.com/ms-azurequantum/AzureQuantum/_build/results?buildId=175699&view=logs&j=952087fc-9883-5ff3-db1f-8bada3bf11c0&t=5277f9f7-4ef6-5285-f8b4-575ec02ad50a&l=55641)

This looks like a conflict between problem `libblis` and `libflame`, introduced by #622 using of `blas::rot`.
